### ISSUE TITLE
error: ImportError: No module named datasets.synthp

### ISSUE THREAD

**Issue by ghost** [clinicalml/structuredinference#1]
Hi, I was trying to run VisualizeSynthetic in Ipython notebook, but always meet the following error:
My running env is ubuntu server 14.04 with theanomodels, pykalman installed and tested, also with cuda
8.0 correctly installed.  Any one save me?

ImportError                               Traceback (most recent call last)
<ipython-input-8-d150b0100b4d> in <module>()
     17 #http://stackoverflow.com/questions/22408237/named-colors-in-matplotlib
     18 import cPickle as pickle
---> 19 from datasets.synthp import params_synthetic
     20 
     21 #visualize synthetic results

ImportError: No module named datasets.synthp

**Comment by rahulk90** [comment]
datasets.synthp is in theanomodels https://github.com/clinicalml/theanomodels/blob/master/datasets/synthp.py

If you've added theanomodels to your PYTHONPATH it should work. 

Try running the import first from the folder in theanomodels:

```
bash$ python
>>> from datasets.synthp import params_synthetic
```

and then from the ipython notebook. If you just installed the module you might have to do 

```
source ~/.bashrc 
```

for the changes to take effect in your shell.

**Comment by ghost** [comment]
Thanks! It works in bash, i can now import, i guess i might forgot to do source ~/.bashrc.
However, in Ipython notebook there still remain the same error.

**Comment by rahulk90** [comment]
If it works in bash, it should work in the notebook. Try restarting your server after doing source ~/.profile

**Comment by rahulk90** [comment]
Did that work for you?

**Comment by ghost** [comment]
Hi, @rahulk90  Thank you!
I have installed theanomodels and added theanomodels to my PYTHONPATH,
it works fine in bash. However, after restarting server there still remain error in Ipython notebook as follows:
My environment is ubuntu 14.04 with python 2.7.6, but using pyenv, maybe this cause this strange problem?

---

ImportError                               Traceback (most recent call last)
<ipython-input-8-d150b0100b4d> in <module>()
     17 #http://stackoverflow.com/questions/22408237/named-colors-in-matplotlib
     18 import cPickle as pickle
---> 19 from datasets.synthp import params_synthetic
     20 
     21 #visualize synthetic results

ImportError: No module named datasets.synthp

**Comment by ghost** [comment]
Hi, @rahulk90 , on another machine, things goes seems more smoothly. But i am not sure if i missed some steps for obtaining data because when i run ipython notebook in synthetic folder it shows as follows:  Could any one help me? Thanks

---

IOError                                   Traceback (most recent call last)
<ipython-input-1-2ed5a7e3a1d0> in <module>()
     44 
     45 bline = '../../expt-synthetic-fast/baselines/'+dataset+'-baseline.h5'
---> 46 baseline = getHDF5Data(bline)
     47 
     48 from datasets.load import loadDataset

<ipython-input-1-2ed5a7e3a1d0> in getHDF5Data(f)
     27 
     28 def getHDF5Data(f):
---> 29     ff = h5py.File(f,mode='r')
     30     alldata = {}
     31     for k in ff.keys():

/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.pyc in __init__(self, name, mode, driver, libver, userblock_size, swmr, *_kwds)
    270 
    271                 fapl = make_fapl(driver, libver, *_kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273 
    274                 if swmr_support:

/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.pyc in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     90         if swmr and swmr_support:
     91             flags |= h5f.ACC_SWMR_READ
---> 92         fid = h5f.open(name, flags, fapl=fapl)
     93     elif mode == 'r+':
     94         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

/usr/lib/python2.7/dist-packages/h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)()
     52     lock is needed, it acquires the lock and notifies the first thread
     53     to release it when it's done.  This is all made possible by the
---> 54     wonderful GIL.
     55     """
     56     cdef pythread.PyThread_type_lock _real_lock

/usr/lib/python2.7/dist-packages/h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)()
     53     to release it when it's done.  This is all made possible by the
     54     wonderful GIL.
---> 55     """
     56     cdef pythread.PyThread_type_lock _real_lock
     57     cdef long _owner            # ID of thread owning the lock

/usr/lib/python2.7/dist-packages/h5py/h5f.pyx in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)()
     74 def create(char\* name, int flags=H5F_ACC_TRUNC, PropFCID fcpl=None,
     75                                                 PropFAID fapl=None):
---> 76     """(STRING name, INT flags=ACC_TRUNC, PropFCID fcpl=None,
     77     PropFAID fapl=None) => FileID
     78 

IOError: Unable to open file (Unable to open file: name = '../../expt-synthetic-fast/baselines/synthetic11-baseline.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by ghost** [comment]
Could anyone help me the above problem? Thanks!

**Comment by rahulk90** [comment]
In order to generate the file '../../expt-synthetic-fast/baselines/synthetic11-baseline.h5'
you will need to run the file run_baselines.py in the folder expt-synthetic-fast/

**Comment by ghost** [comment]
Thanks!

**Comment by rahulk90** [comment]
Closing issue
