### ISSUE TITLE
Supporting params['data_type']=real

### ISSUE THREAD

**Issue by lionwarriorjr** [clinicalml/structuredinference#4]
In the model implementation for dkf (dkf.py), it seems like only binary data types are supported, shown below. Must we discretize continuous observations to use the model? The paper mentions binning A1c levels and glucose into clinically meaningful bins and quantiles, respectively.

```
if self.params['data_type']=='binary':
            npWeights['p_emis_W_ber'] = self._getWeight((self.params['dim_hidden'], self.params['dim_observations']))
            npWeights['p_emis_b_ber'] = self._getWeight((self.params['dim_observations'],))
elif self.params['data_type']=='binary_nade':
            n_visible, n_hidden   = self.params['dim_observations'], self.params['dim_hidden']
            npWeights['p_nade_W'] = self._getWeight((n_visible, n_hidden))
            npWeights['p_nade_U'] = self._getWeight((n_visible,n_hidden))
            npWeights['p_nade_b'] = self._getWeight((n_visible,))
else:
            assert False,'Invalid datatype: '+params['data_type']
```

**Comment by rahulk90** [comment]
Hey, this is a much cleaner repository with code for the same model: 
https://github.com/clinicalml/dmm

It might be easier both to read at and modify.

I've added a reference to the code in the model that sets up evaluation of the real-valued likelihood. 
https://github.com/clinicalml/dmm/blob/master/model_th/dmm.py#L191

**Comment by lionwarriorjr** [comment]
Thank you. This file, in particular the notebooks in the repo, are very helpful for following along.

In the dmm.py file you commented on, where can I specify the control inputs U (since in our case they are also always known) at each timestep?
