### ISSUE TITLE
What is utils that is imported in dfk.py files?

### ISSUE THREAD

**Issue by hrezaeianzadeh** [clinicalml/structuredinference#5]

**Comment by CJHJ** [comment]
The utils comes from the theanomodels library listed in the readme. You can download it here https://github.com/clinicalml/theanomodels

Clone it and then add the path to it to PYTHONPATH.

**Comment by rahulk90** [comment]
Thanks for the response! I also want to point out that a more user-friendly version of the code is available here: https://github.com/clinicalml/dmm
